//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sms.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSku
    {
        public int SkuId { get; set; }
        public int ItemId { get; set; }
        public string Name { get; set; }
        public decimal SalePrice { get; set; }
        public bool isDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
    
        public virtual ItemInfo ItemInfo { get; set; }
    }
}
