//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sms.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCard
    {
        public string CardNo { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Banlance { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<decimal> TotalPresent { get; set; }
    }
}
