//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sms.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmsEntities : DbContext
    {
        public SmsEntities()
            : base("name=SmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardHistory> CardHistory { get; set; }
        public virtual DbSet<MemberCard> MemberCard { get; set; }
        public virtual DbSet<Promotion> Promotion { get; set; }
        public virtual DbSet<SysLog> SysLog { get; set; }
        public virtual DbSet<SystemModule> SystemModule { get; set; }
        public virtual DbSet<SystemModuleRight> SystemModuleRight { get; set; }
        public virtual DbSet<SystemRole> SystemRole { get; set; }
        public virtual DbSet<SystemRoleRight> SystemRoleRight { get; set; }
        public virtual DbSet<SystemUser> SystemUser { get; set; }
        public virtual DbSet<WeChatMember> WeChatMember { get; set; }
        public virtual DbSet<WechatMemberPointsLog> WechatMemberPointsLog { get; set; }
        public virtual DbSet<ItemBrand> ItemBrand { get; set; }
        public virtual DbSet<ItemCategory> ItemCategory { get; set; }
        public virtual DbSet<ItemSku> ItemSku { get; set; }
        public virtual DbSet<ItemUnionCategory> ItemUnionCategory { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersDetail> OrdersDetail { get; set; }
        public virtual DbSet<ItemInfo> ItemInfo { get; set; }
    }
}
