//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sms.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeChatMember
    {
        public string OpenId { get; set; }
        public string NickName { get; set; }
        public string Mobile { get; set; }
        public string AvatarUrl { get; set; }
        public int Gender { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string UnionId { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string SessionKey { get; set; }
        public int Rank { get; set; }
        public int AvailablePoints { get; set; }
        public int TotalPoints { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    }
}
