//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sms.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WechatMemberPointsLog
    {
        public string Id { get; set; }
        public string OpenId { get; set; }
        public int Type { get; set; }
        public string BillCode { get; set; }
        public int BeforeValue { get; set; }
        public int ChangeValue { get; set; }
        public int AfterValue { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
